# Generated by Django 6.0.1 on 2026-07-21 20:58

import Tasks.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=150, null=True)),
                ('state', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CHECKING', 'CHECKING')], default='ASSIGNED', max_length=11)),
                ('deadline', models.DateTimeField(default=Tasks.models.default_deadline_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='Members.projectmanager')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='Members.member')),
            ],
        ),
    ]
