# Generated by Django 6.0.1 on 2026-07-21 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_delete_lead'),
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedByTask', to='Members.member'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedToTask', to='Members.member'),
        ),
    ]
