# Generated by Django 6.0.1 on 2026-07-19 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('availability', models.BooleanField(default=False)),
                ('department', models.CharField(choices=[('backend', 'BACKEND'), ('frontend', 'FRONTEND'), ('QA', 'QA'), ('tester', 'TESTER'), ('AI', 'AI')])),
                ('role', models.CharField(choices=[('intern', 'INTERN'), ('junior', 'JUNIOR'), ('senior', 'SENIOR')], default='intern')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
