# Generated by Django 6.0.1 on 2026-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('backend', 'BACKEND'), ('frontend', 'FRONTEND'), ('QA', 'QA'), ('tester', 'TESTER'), ('AI', 'AI'), ('PM', 'PM')]),
        ),
    ]
