# Generated by Django 6.0.1 on 2026-07-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
