# Generated by Django 6.0.1 on 2026-07-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_delete_lead'),
        ('Tasks', '0002_alter_taskmodel_assigned_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectManager',
        ),
    ]
